### ISSUE TITLE
ip_protocol_fallback not defaulting to true

### ISSUE THREAD

**Issue by 3nin6** [prometheus/blackbox_exporter#424]
### Host operating system: output of `uname -a`
running docker, latest image.
prom/blackbox-exporter     latest       93b0a39952e7        26 hours ago

blackbox_exporter_build_info
branch="HEAD"
goversion="go1.11.5"
revision="434fdfca09c6af57d87ed71acf0035cb7f8003f4"
version="0.14.0"

### What is the blackbox.yml module config.

  http_notregex:
    prober: http
    timeout: 15s
    http:
      fail_if_body_not_matches_regexp:
        - "regexthis"

### What is the prometheus.yml scrape config.
n/a

### What logging output did you get from adding `&debug=true` to the probe URL?
n/a

### What did you do that produced an error?
updated to latest

### What did you expect to see?
success on probes.

### What did you see instead?
failures due to blackbox not finding ip6 and then failing to fallback to ipv4 per defaults in https://github.com/prometheus/blackbox_exporter/blob/master/CONFIGURATION.md
-- this occurred in http and icmp probes i am using.

switching to explicitly defining fallback true corrected the issue for my http and icmp probes:

  http_notregex:
    prober: http
    timeout: 15s
    http:
      ip_protocol_fallback: true
      fail_if_body_not_matches_regexp:
        - "regexthis"

**Comment by brian-brazil** [comment]
This was discovered yesterday, and will be fixed before release.

**Comment by TheUsualSuspekt** [comment]
I'm also getting the exact same behavior with Version V0.14.0, Rolling back to V0.13.0 works perfectly.

**Comment by laghoule** [comment]
This MR https://github.com/prometheus/blackbox_exporter/pull/436 should fix the issue.
Please test / review / comments.

**Comment by mitchellrj** [comment]
Doesn't seem fixed to me. I'm still seeing this failure, even with a fresh build from `master`

```
blackbox_exporter_build_info{branch="HEAD",goversion="go1.11.4",instance="localhost:9115",job="prometheus",revision="bba7ef76193948a333a5868a1ab38b864f7d968a",version="0.14.0"}
```

Config:
```
modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
```

Probe with debug:
```
Logs for the probe:
ts=2019-03-22T21:28:14.877816532Z caller=main.go:118 module=http_2xx target="http://192.168.7.107:8008/setup/eureka_info?options=detail" level=info msg="Beginning probe" probe=http timeout_seconds=4.5
ts=2019-03-22T21:28:14.878447777Z caller=utils.go:42 module=http_2xx target="http://192.168.7.107:8008/setup/eureka_info?options=detail" level=info msg="Resolving target address" ip_protocol=ip6
ts=2019-03-22T21:28:14.878562828Z caller=utils.go:53 module=http_2xx target="http://192.168.7.107:8008/setup/eureka_info?options=detail" level=error msg="Resolution with IP protocol failed (fallback_ip_protocol is false):" err="address 192.168.7.107: no suitable address found"
ts=2019-03-22T21:28:14.878665692Z caller=http.go:276 module=http_2xx target="http://192.168.7.107:8008/setup/eureka_info?options=detail" level=error msg="Error resolving address" err="address 192.168.7.107: no suitable address found"
ts=2019-03-22T21:28:14.878745743Z caller=main.go:131 module=http_2xx target="http://192.168.7.107:8008/setup/eureka_info?options=detail" level=error msg="Probe failed" duration_seconds=0.000744786
```

**Comment by laghoule** [comment]
Remove the last line of your config:
`http:`

And try again

**Comment by mitchellrj** [comment]
Ah. So if I defined the `http` block but didn't specify that key explicitly
already, the suggested default wouldn't work. That sounds like a backwards
incompatibility to me - I'm disappointed this wasn't documented more
clearly in the release notes.

**Comment by swiffer** [comment]
same here - removing the blank `http:` line solves the problem - could have been pointed out more clearly in release info - anyway thanks for your great work!!
