### ISSUE TITLE
new release 0.20.0 ?

### ISSUE THREAD

**Issue by ermalbaj** [prometheus/blackbox_exporter#848]
Do you have any plan for a new release?
Seem like its more then 6 months and it is not maintained anymore.
Any info would be helpfully...thanks
Ermali

**Comment by roidelapluie** [comment]
I'll release a RC soon.

**Comment by ermalbaj** [comment]
we will get something for this year?

**Comment by MarkusTeufelberger** [comment]
No. But maybe 2022, please?

**Comment by SuperQ** [comment]
Yes, I'm working on cleaning a few things up so we can make a release.

**Comment by roidelapluie** [comment]
We have released 0.20.0-rc.0.

**Comment by hillbun** [comment]
@roidelapluie 

It seems that probe_ip_addr_hash bug is not solved yet

**Comment by hillbun** [comment]
@roidelapluie 

issue is here

https://github.com/prometheus/blackbox_exporter/issues/875

**Comment by hillbun** [comment]
@SuperQ   How to solve #875 issue, please advice , thanks.

**Comment by foosinn** [comment]
@roidelapluie i think this issue can be closed
